version: "3"

services:
    receiver:
        build:
            context: ./receiver
            dockerfile: Dockerfile
        image: "receiver:latest"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
    supercollider:
        build:
            context: ./supercollider-extra
            dockerfile: Dockerfile
        image: "supercollider-extra:3.11.1"
    espnet-tts:
        build:
            context: ./espnet
            dockerfile: Dockerfile
        image: "espnet-tts:latest"
        command: /bin/bash -c "tail -f /var/log/access.log -f /var/log/error.log"
        environment:
            - TORCH_DEVICE=cuda
        deploy:
            resources:
                reservations:
                    devices:
                    - driver: nvidia
                      capabilities: ["gpu", "utility", "compute"]
