config: conf/train.yaml
print_config: false
log_level: INFO
dry_run: false
iterator_type: sequence
output_dir: exp/tts_train_raw_phn_tacotron_espeak_ng_french
ngpu: 1
seed: 0
num_workers: 1
num_att_plot: 3
dist_backend: nccl
dist_init_method: env://
dist_world_size: null
dist_rank: null
local_rank: 0
dist_master_addr: null
dist_master_port: null
dist_launcher: null
multiprocessing_distributed: false
unused_parameters: false
sharded_ddp: false
cudnn_enabled: true
cudnn_benchmark: false
cudnn_deterministic: true
collect_stats: false
write_collected_feats: false
max_epoch: 300
patience: null
val_scheduler_criterion:
- valid
- loss
early_stopping_criterion:
- valid
- loss
- min
best_model_criterion:
-   - valid
    - loss
    - min
-   - train
    - loss
    - min
keep_nbest_models: 5
nbest_averaging_interval: 0
grad_clip: 1.0
grad_clip_type: 2.0
grad_noise: false
accum_grad: 1
no_forward_run: false
resume: true
train_dtype: float32
use_amp: false
log_interval: null
use_matplotlib: true
use_tensorboard: true
create_graph_in_tensorboard: false
use_wandb: false
wandb_project: null
wandb_id: null
wandb_entity: null
wandb_name: null
wandb_model_log_interval: -1
detect_anomaly: false
pretrain_path: null
init_param: []
ignore_init_mismatch: false
freeze_param: []
num_iters_per_epoch: 500
batch_size: 20
valid_batch_size: null
batch_bins: 5120000
valid_batch_bins: null
train_shape_file:
- exp/tts_stats_raw_phn_tacotron_espeak_ng_french/train/text_shape.phn
- exp/tts_stats_raw_phn_tacotron_espeak_ng_french/train/speech_shape
valid_shape_file:
- exp/tts_stats_raw_phn_tacotron_espeak_ng_french/valid/text_shape.phn
- exp/tts_stats_raw_phn_tacotron_espeak_ng_french/valid/speech_shape
batch_type: numel
valid_batch_type: null
fold_length:
- 150
- 204800
sort_in_batch: descending
sort_batch: descending
multiple_iterator: false
chunk_length: 500
chunk_shift_ratio: 0.5
num_cache_chunks: 1024
train_data_path_and_name_and_type:
-   - dump/raw/train/text
    - text
    - text
-   - dump/raw/train/wav.scp
    - speech
    - sound
valid_data_path_and_name_and_type:
-   - dump/raw/valid/text
    - text
    - text
-   - dump/raw/valid/wav.scp
    - speech
    - sound
allow_variable_data_keys: false
max_cache_size: 0.0
max_cache_fd: 32
valid_max_cache_size: null
optim: adam
optim_conf:
    lr: 0.001
    eps: 1.0e-06
    weight_decay: 0.0
scheduler: null
scheduler_conf: {}
token_list:
- <blank>
- <unk>
- ʁ
- s
- l
- t
- d
- a
- k
- p
- n
- m
- .
- ə-
- i
- ə
- ɛ
- z
- ˈi
- v
- j
- ˈa
- o
- u
- ˈɔ̃
- ˈɛ
- y
- ','
- ˈɑ̃
- ɑ̃
- ʒ
- f
- b
- w
- e
- ˈe
- ɔ̃
- ɡ
- a-
- ˈɔ
- e-
- ɔ
- ʃ
- ˈɛ̃
- ˈø
- ˈy
- ˈo
- œ̃
- (en)
- (fr)
- ɛ̃
- ˈu
- ˈœ
- ˈə
- ˌa
- '!'
- ø
- y-
- ɹ
- ˌi
- ˈiː
- '?'
- iː
- ˌiː
- ˌɛ
- ɪ
- ˈʊə
- '...'
- ˌu
- œ
- ɲ
- ˌɔ
- ˌɛ̃
- ˈœ̃
- dʒ
- ˈɪ
- aɪ
- ˌɑ̃
- ˈeɪ
- ˈɒ
- ˈa-
- θ
- ɐ
- ˈɔː
- ˌø
- ˈɜː
- ŋ
- ˈɑː
- ˈəʊ
- ˈuː
- ˌœ
- ˈaʊ
- ˈiə
- ɒ
- ˌɪ
- iə
- ˈʌ
- ɔɪ
- ˌe
- ˈaɪ
- h
- uː
- əʊ
- ˌuː
- ˌə
- tʃ
- ɔː
- ð
- əl
- ˈʊ
- eɪ
- ˈeə
- ˈə-
- ˌiə
- aʊ
- ɑː
- ˌɔ̃
- ˌaɪ
- ',...'
- ʊ
- ˌœ̃
- ˌɜː
- ˈɔɪ
- ˌɒ
- <sos/eos>
odim: null
model_conf: {}
use_preprocessor: true
token_type: phn
bpemodel: null
non_linguistic_symbols: null
cleaner: tacotron
g2p: espeak_ng_french
feats_extract: fbank
feats_extract_conf:
    n_fft: 1024
    hop_length: 256
    win_length: null
    fs: 22050
    fmin: 80
    fmax: 7600
    n_mels: 80
normalize: global_mvn
normalize_conf:
    stats_file: /services/espnet-tts-fr/conf/model-conf/feats_stats.npz
tts: tacotron2
tts_conf:
    embed_dim: 512
    elayers: 1
    eunits: 512
    econv_layers: 3
    econv_chans: 512
    econv_filts: 5
    atype: location
    adim: 512
    aconv_chans: 32
    aconv_filts: 15
    cumulate_att_w: true
    dlayers: 2
    dunits: 1024
    prenet_layers: 2
    prenet_units: 256
    postnet_layers: 5
    postnet_chans: 512
    postnet_filts: 5
    output_activation: null
    use_batch_norm: true
    use_concate: true
    use_residual: false
    dropout_rate: 0.5
    zoneout_rate: 0.1
    reduction_factor: 1
    spk_embed_dim: null
    use_masking: true
    bce_pos_weight: 5.0
    use_guided_attn_loss: true
    guided_attn_loss_sigma: 0.4
    guided_attn_loss_lambda: 1.0
pitch_extract: null
pitch_extract_conf: {}
pitch_normalize: null
pitch_normalize_conf: {}
energy_extract: null
energy_extract_conf: {}
energy_normalize: null
energy_normalize_conf: {}
required:
- output_dir
- token_list
version: '202209'
distributed: false
