import express from "express";
import sharp from "sharp";
import Ajv from "ajv";
import Articles from "articles";

import querySchemaJSON from "./schemas/request.schema.json";
import handlerResponseSchemaJSON from "./schemas/handler-response.schema.json";
import definitionsJSON from "./schemas/definitions.json";

const app = express();
const port = 80;
const ajv = new Ajv({
    "schemas": [querySchemaJSON, definitionsJSON, handlerResponseSchemaJSON] 
});

async function extractDimensions(dataUrl: string) {
    const imageBuffer = Buffer.from(dataUrl.split(",")[1], "base64");
    const metadata = await sharp(imageBuffer).metadata();
    return [metadata.width as number, metadata.height as number];
}

async function extractBoundingBox(dataUrl:string){
    

    return []; //return array of boundingboxes

}

function calcConfidence(objects: Record<string, unknown>[]): number {
    let confidence = objects.reduce((acc, cur) => {
        acc += cur["confidence"] as number;
        return acc;
    }, 0);
    confidence /= objects.length;
    return confidence;
}

function generateRendering(width: number, height: number): object {
    return {
        "type_id": "ca.mcgill.a11y.image.renderer.simpleHaptics",
        "confidence": calcConfidence(objectData["objects"]),
        "description": "Bounding Box informaiton for haptic roundtrip example.",
        "metadata": {
            "description": "This was generated by the \"hello haptics handler\" container, an to test a roundtrip for haptic renderings. It is not meant to be used in production."
        },
        "dimensions": {
            items: {}
            
        }
    };
}

app.use(express.json({ limit: process.env.MAX_BODY }));

app.post("/handler", async (req, res) => {
    if (ajv.validate("https://image.a11y.mcgill.ca/request.schema.json", req.body)) {
        console.log("Request validated");
        if (!req.body.image) {
            console.log("Not an image request! Skipping...");
            res.status(204);
            return;
        }
        // Check for text rendering support
        const renderers = req.body.renderers as string[];
        const rendering = [];
        if (renderers.includes("ca.mcgill.a11y.image.renderer.simpleHaptics")) {
            const dims = await extractBoundingBox() // call the json extraction function
            rendering.push(generateRendering(dims[0], dims[1])); // call modified generateRendering 
        } else {
            console.warn("Text renderer not supported by the client!");
        }
        const response = {
            "request_uuid": req.body.request_uuid,
            "timestamp": Math.round(Date.now() / 1000),
            "renderings": rendering 
        };
        if (ajv.validate("https://image.a11y.mcgill.ca/handler-response.schema.json", response)) {
            console.log("Valid response generated.");
            res.json(response);
        } else {
            console.log("Failed to generate a valid response (did the schema change?)");
            res.status(500).json(ajv.errors);
        }
    } else {
        console.log("Request did not pass the schema.");
        res.status(400).send(ajv.errors);
    }
});

app.listen(port, () => {
    console.log(`Started server on port ${port}`);
});
