#!/usr/bin/sh

# usage: bsu [image-name]
# build, stop, up -d an image in the docker-compose.
# useful when making changes to preprocessors and handlers,
# and wanting to bring up the new version to test it out.
# 
# NOTE: Assumes name of image and container are the same.
# 
# maintainer: jeffbl

docker compose build $1 && docker compose stop $1 && docker compose up -d $1