"""
LLM utilities.
"""

from .client import LLMClient
from .prompts import (
    MULTISTAGE_DIAGRAM_BASE_PROMPT,
    BOUNDING_BOX_PROMPT_TEMPLATE,
    BOUNDING_BOX_PROMPT_EXAMPLE,
    GRAPHIC_CAPTION_PROMPT,
    CATEGORISER_PROMPT,
    FOLLOWUP_PROMPT,
    FOLLOWUP_PROMPT_FOCUS,
    OBJECT_DETECTION_PROMPT
)

__all__ = [
    'LLMClient',
    'MULTISTAGE_DIAGRAM_BASE_PROMPT',
    'BOUNDING_BOX_PROMPT_TEMPLATE',
    'BOUNDING_BOX_PROMPT_EXAMPLE',
    'GRAPHIC_CAPTION_PROMPT',
    'CATEGORISER_PROMPT',
    'FOLLOWUP_PROMPT',
    'FOLLOWUP_PROMPT_FOCUS',
    'OBJECT_DETECTION_PROMPT'
]
