name: Hello SVG Handler
on:
  push:
    branches: [ main ]
    paths: [ "handlers/hello-svg-handler/**" ]
  pull_request:
    branches: [ main ]
    paths: [ "handlers/hello-svg-handler/**" ]
  workflow_dispatch:
jobs:
  lint:
    name: PEP 8 style check.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install flake8
        run: pip install flake8
      - name: Check with flake8
        run: python -m flake8 ./handlers/hello-svg-handler --show-source
  build-image:
    name: Build and Don't Push
    needs: lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Build
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./handlers/hello-svg-handler/Dockerfile
          push: false
