name: Object Detection with LLM
on:
  push:
    branches: [ main, object-detection-llm ]
    tags: [ "preprocessor-object-detection-llm-[0-9]+.[0-9]+.[0-9]+" ]
    paths: [ "preprocessors/object-detection-llm/**" ]
  pull_request:
    branches: [ main ]
    paths: [ "preprocessors/object-detection-llm/**" ]
  workflow_run:
    workflows: [ "Schemas (Trigger)" ]
    types:
      - completed
  workflow_dispatch:
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: shared-reality-lab/image-preprocessor-object-detection-llm
jobs:
  lint:
    name: PEP 8 style check.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install flake8
        run: pip install flake8
      - name: Check with flake8
        run: python -m flake8 ./preprocessors/object-detection-llm --show-source
  build-and-push-image:
    name: Build and Push to Registry
    needs: lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Log into GHCR
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Get Correct Tags
        run: |
          if [[ ${{ github.ref }} =~ ^refs/tags/preprocessor-object-detection-llm-[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "TAGGED=true" >> $GITHUB_ENV
          else
            echo "TAGGED=false" >> $GITHUB_ENV
          fi
      - name: Get timestamp
        run: echo "timestamp=$(date -u +'%Y-%m-%dT%H.%M')" >> $GITHUB_ENV
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          flavor: |
            latest=${{ env.TAGGED }}
          tags: |
            type=match,enable=${{ env.TAGGED }},priority=300,pattern=preprocessor-object-detection-llm-(\d+.\d+.\d+),group=1
            type=raw,priority=200,value=unstable
            type=raw,priority=100,value=${{ env.timestamp }}
          labels: |
            org.opencontainers.image.title=IMAGE Preprocessor Object Detection with LLM
            org.opencontainers.image.description=Identifies objects in graphics, provides coordinates of bounding boxes of these objects.
            org.opencontainers.image.authors=IMAGE Project <image@cim.mcgill.ca>
            org.opencontainers.image.documentation=https://github.com/Shared-Reality-Lab/IMAGE-server/tree/main/preprocessors/object-detection-llm/README.md
            org.opencontainers.image.licenses=AGPL-3.0-or-later
            maintainer=IMAGE Project <image@cim.mcgill.ca>
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./preprocessors/object-detection-llm/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
