name: OSM Preprocessor
on:
  push:
    branches: [ main ]
    paths: [ "preprocessors/openstreet/**" ]
  pull_request:
    branches: [ main ]
    paths: [ "preprocessors/openstreet/**" ]
  workflow_dispatch:
jobs:
  lint:
    name: PEP 8 style check.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install flake8
        run: pip install flake8
      - name: Check with flake8
        run: python -m flake8 ./preprocessors/openstreet --show-source
