name: Schema
on:
  push:
    branches: [ schemas ]
  pull_request:
    branches: [ schemas ]
  workflow_dispatch:
jobs:
  compile:
    name: Compile schema with ajv-cli
    runs-on: ubuntu-latest
    steps:
      - if: github.ref
        uses: actions/checkout@v2
      - if: !github.ref
        uses: actions/checkout@v2
        with:
          ref: schemas
      - uses: actions/setup-node@v2
      - name: Install ajv-cli
        run: npm i -g ajv-cli
      - name: Compile schemas
        run: ajv compile -s "**/*.json"
