name: Semantic Segmentation
on:
  push:
    branches: [ main ]
    paths: [ "preprocessors/semanticSeg/**" ]
  pull_request:
    branches: [ main ]
    paths: [ "preprocessors/semanticSeg/**" ]
  workflow_dispatch:
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: shared-reality-lab/image-preprocessor-semantic-segmentation
jobs:
  lint:
    name: PEP 8 style check.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install flake8
        run: pip install flake8
      - name: Check with flake8
        run: python -m flake8 ./preprocessors/semanticSeg --show-source
  build-and-push-image:
    name: Build and Push to Registry
    needs: lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Log into GHCR
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha
          labels: |
            org.opencontainers.image.title=IMAGE Preprocessor Semantic Segmentation
            org.opencontainers.image.description=Semantic segmentation preprocessor for IMAGE.
            org.opencontainers.image.authors=IMAGE Project <image@cim.mcgill.ca>
            org.opencontainers.image.licenses=AGPL-3.0-or-later
            maintainer=IMAGE Project <image@cim.mcgill.ca>
      - name: Get timestamp
        run: echo "timestamp=$(date -u +'%Y-%m-%dT%H.%M')" >> $GITHUB_ENV
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./preprocessors/semanticSeg/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:unstable
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.timestamp }}
          labels: ${{ steps.meta.outputs.labels }}
