name: Supercollider Service
on:
  push:
    branches: [ main ]
    tags: [ "service-supercollider-[0-9]+.[0-9]+.[0-9]+" ]
    paths: [ "services/supercollider-images/supercollider-service/**" ]
  workflow_dispatch:
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: shared-reality-lab/image-service-supercollider
jobs:
  build-and-push-image:
    name: Build and Push to Registry
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Log into GHCR
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Get Correct Tags
        run: |
          if [[ ${{ github.ref }} =~ ^refs/tags/service-supercollider-[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "TAGGED=true" >> $GITHUB_ENV
          else
            echo "TAGGED=false" >> $GITHUB_ENV
          fi
      - name: Get timestamp
        run: echo "timestamp=$(date -u +'%Y-%m-%dT%H.%M')" >> $GITHUB_ENV
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          flavor: |
            latest=${{ env.TAGGED }}
          tags: |
            type=match,enable=${{ env.TAGGED }},priority=300,pattern=service-supercollider-(\d+.\d+.\d+),group=1
            type=raw,priority=200,value=unstable
            type=raw,priority=100,value=${{ env.timestamp }}
          labels: |
            org.opencontainers.image.title=IMAGE Service Supercollider
            org.opencontainers.image.description=Supercollider-based service for audio synthesis used in IMAGE.
            org.opencontainers.image.authors=IMAGE Project <image@cim.mcgill.ca>
            org.opencontainers.image.documentation=https://github.com/Shared-Reality-Lab/IMAGE-server/tree/main/services/supercollider-images/supercollider-service/README.md
            org.opencontainers.image.licenses=AGPL-3.0-or-later
            maintainer=IMAGE Project <image@cim.mcgill.ca>
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./services/supercollider-images/supercollider-service/
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
